version: "3.8"

services:
  backend:
    image: josemaaa/practica-final:final # Imagen del backend en Docker Hub
    container_name: agenda-backend-compose
    ports:
      - "8080:8080"
    networks:
      - josema-network

  frontend:
    image: josemaaa/practica-finalweb:final # Imagen del frontend en Docker Hub
    container_name: agenda-frontend-compose
    ports:
      - "4200:80" # Mapea el puerto 80 del contenedor al 4200 en la máquina
    networks:
      - josema-network

networks:
  josema-network:
    driver: bridge
